# -*- coding: utf-8 -*-
"""3-VWAP Mean Reversion

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aCF-LRjx_TvBnsYaeDjxgZCi0_xTakU8
"""

# ============================================================
# CELL 1 - Εγκατάσταση + Σήμα Extreme 3-VWAP
# ============================================================

# Εγκατάσταση απαραίτητων πακέτων
!pip install -q pandas_ta

import numpy as np
import pandas as pd
import pandas_ta as ta

def calculate_vwap(df: pd.DataFrame, window: int | None = None) -> pd.Series:
    """Session VWAP (window=None) or rolling VWAP"""
    tp = (df["high"] + df["low"] + df["close"]) / 3.0
    if window is None:
        # Session VWAP – resets every day
        dates = df.index.date
        cum_vol = df["volume"].groupby(dates).cumsum()
        cum_tp_vol = (tp * df["volume"]).groupby(dates).cumsum()
        return cum_tp_vol / cum_vol
    else:
        return (tp * df["volume"]).rolling(window, min_periods=1).sum() / \
               df["volume"].rolling(window, min_periods=1).sum()

def make_extreme_3vwap_signal(
    df: pd.DataFrame,
    # --- Best parameters found ---
    band: float = 0.00616,          # ~0.616%
    adx_th: float = 20.93,          # ADX must be BELOW this (ranging)
    vol_mult: float = 1.90,         # Volume > 1.90 × MA20
    sl_pct: float = 0.00377,        # 1:1
    tp_pct: float = 0.00377,
    bias: str = "short_only",       # "both" | "long_only" | "short_only"
    use_rejection: bool = False,
) -> pd.Series:
    """
    Returns signal Series:
        1  = Long
       -1  = Short
        0  = Flat
    """
    required = ["open", "high", "low", "close", "volume"]
    if not all(c in df.columns for c in required):
        raise ValueError(f"DataFrame must contain: {required}")

    df = df.copy()

    # ========== 3 VWAPs ==========
    df["vwap_sess"] = calculate_vwap(df, None)       # Session
    df["vwap_12"]   = calculate_vwap(df, 12)         # ~1 hour
    df["vwap_78"]   = calculate_vwap(df, 78)         # ~6.5 hours

    # ========== ADX ==========
    adx_df = ta.adx(df["high"], df["low"], df["close"], length=14)
    df["adx"] = adx_df["ADX_14"]

    # ========== Volume ==========
    df["vol_ma20"] = df["volume"].rolling(20).mean()
    df["vol_ma10"] = df["volume"].rolling(10).mean()

    # ========== Clean ==========
    df = df.dropna()

    close = df["close"]
    high  = df["high"]
    low   = df["low"]
    vol   = df["volume"]
    adx   = df["adx"]
    open_ = df["open"]

    v1 = df["vwap_sess"]
    v2 = df["vwap_12"]
    v3 = df["vwap_78"]

    # ========== Core Conditions ==========
    long_cond = (
        (close < v1 * (1 - band)) &
        (close < v2 * (1 - band)) &
        (close < v3 * (1 - band)) &
        (adx < adx_th) &
        (vol > df["vol_ma20"] * vol_mult) &
        (vol > df["vol_ma10"] * 1.1)
    )

    short_cond = (
        (close > v1 * (1 + band)) &
        (close > v2 * (1 + band)) &
        (close > v3 * (1 + band)) &
        (adx < adx_th) &
        (vol > df["vol_ma20"] * vol_mult) &
        (vol > df["vol_ma10"] * 1.1)
    )

    # Optional rejection candle
    if use_rejection:
        long_cond  = long_cond  & (close > open_)
        short_cond = short_cond & (close < open_)

    # ========== Build Signal ==========
    signal = pd.Series(0, index=df.index, dtype=int)
    signal[long_cond]  = 1
    signal[short_cond] = -1

    if bias == "long_only":
        signal = signal.where(signal == 1, 0)
    elif bias == "short_only":
        signal = signal.where(signal == -1, 0)

    return signal

# ============================================================
# Παράδειγμα χρήσης (αφού έχεις φορτώσει το df)
# ============================================================
# signal = make_extreme_3vwap_signal(
#     df,
#     band=0.00616,
#     adx_th=20.93,
#     vol_mult=1.90,
#     bias="short_only",
#     use_rejection=False
# )
# print(signal.value_counts())

# ============================================================
# ΠΛΗΡΕΣ CELL - Φόρτωση δεδομένων + Σήμα + Αποτελέσματα
# ============================================================

!pip install -q kagglehub pandas_ta

import os
import numpy as np
import pandas as pd
import pandas_ta as ta
import kagglehub

# ---------- 1. Φόρτωση δεδομένων NQ ----------
path = kagglehub.dataset_download("salaheddineelkhirani/5-year-data-for-s-and-p-500-and-nasdaq-100")
nq_file = os.path.join(path, "NQ_5Years_8_11_2024.csv")

df = pd.read_csv(nq_file)
df.columns = [c.strip().lower() for c in df.columns]
df["time"] = pd.to_datetime(df["time"])
df = df.set_index("time").sort_index()
df = df[["open", "high", "low", "close", "volume"]].copy()
print(f"Δεδομένα φορτώθηκαν: {df.shape}")
print(f"Από {df.index.min()} έως {df.index.max()}")

# ---------- 2. Συναρτήσεις ----------
def calculate_vwap(df, window=None):
    tp = (df["high"] + df["low"] + df["close"]) / 3.0
    if window is None:
        dates = df.index.date
        cum_vol = df["volume"].groupby(dates).cumsum()
        cum_tp_vol = (tp * df["volume"]).groupby(dates).cumsum()
        return cum_tp_vol / cum_vol
    else:
        return (tp * df["volume"]).rolling(window, min_periods=1).sum() / df["volume"].rolling(window, min_periods=1).sum()

def make_extreme_3vwap_signal(df, band=0.00616, adx_th=20.93, vol_mult=1.90, bias="short_only", use_rejection=False):
    df = df.copy()
    df["vwap_sess"] = calculate_vwap(df, None)
    df["vwap_12"]   = calculate_vwap(df, 12)
    df["vwap_78"]   = calculate_vwap(df, 78)

    adx_df = ta.adx(df["high"], df["low"], df["close"], length=14)
    df["adx"] = adx_df["ADX_14"]
    df["vol_ma20"] = df["volume"].rolling(20).mean()
    df["vol_ma10"] = df["volume"].rolling(10).mean()
    df = df.dropna()

    close = df["close"]
    vol = df["volume"]
    adx = df["adx"]
    open_ = df["open"]
    v1, v2, v3 = df["vwap_sess"], df["vwap_12"], df["vwap_78"]

    long_cond = (
        (close < v1*(1-band)) & (close < v2*(1-band)) & (close < v3*(1-band)) &
        (adx < adx_th) & (vol > df["vol_ma20"]*vol_mult) & (vol > df["vol_ma10"]*1.1)
    )
    short_cond = (
        (close > v1*(1+band)) & (close > v2*(1+band)) & (close > v3*(1+band)) &
        (adx < adx_th) & (vol > df["vol_ma20"]*vol_mult) & (vol > df["vol_ma10"]*1.1)
    )

    if use_rejection:
        long_cond = long_cond & (close > open_)
        short_cond = short_cond & (close < open_)

    signal = pd.Series(0, index=df.index, dtype=int)
    signal[long_cond] = 1
    signal[short_cond] = -1

    if bias == "long_only":
        signal = signal.where(signal == 1, 0)
    elif bias == "short_only":
        signal = signal.where(signal == -1, 0)

    return signal

# ---------- 3. Δημιουργία σήματος ----------
signal = make_extreme_3vwap_signal(df, band=0.00616, adx_th=20.93, vol_mult=1.90, bias="short_only")
print("\nΚατανομή σημάτων:")
print(signal.value_counts())

# ---------- 4. Backtest με αναλυτικές συναλλαγές ----------
def backtest_with_trades(df, signal, sl_pct=0.00377, tp_pct=0.00377, cost=0.00012):
    signal = signal.reindex(df.index).fillna(0).astype(int)

    close = df["close"].values
    high  = df["high"].values
    low   = df["low"].values
    times = df.index.to_numpy()
    sig   = signal.values

    position = 0
    entry_price = 0.0
    entry_time = None
    entry_idx = 0
    trades = []

    for i in range(1, len(close)):
        if position == 0:
            if sig[i] == 1 and sig[i-1] != 1:
                position = 1
                entry_price = close[i]
                entry_time = times[i]
                entry_idx = i
            elif sig[i] == -1 and sig[i-1] != -1:
                position = -1
                entry_price = close[i]
                entry_time = times[i]
                entry_idx = i

        elif position == 1:
            hit_sl = low[i] <= entry_price * (1 - sl_pct)
            hit_tp = high[i] >= entry_price * (1 + tp_pct)
            if hit_sl or hit_tp or sig[i] != 1:
                if hit_sl:
                    exit_p = entry_price * (1 - sl_pct)
                    reason = "SL"
                elif hit_tp:
                    exit_p = entry_price * (1 + tp_pct)
                    reason = "TP"
                else:
                    exit_p = close[i]
                    reason = "Signal"
                ret = (exit_p / entry_price - 1) - 2 * cost
                trades.append({
                    "entry_time": entry_time,
                    "exit_time": times[i],
                    "direction": "LONG",
                    "entry_price": round(entry_price, 2),
                    "exit_price": round(exit_p, 2),
                    "return_%": round(ret * 100, 3),
                    "result": "WIN" if ret > 0 else "LOSS",
                    "reason": reason,
                    "bars_held": i - entry_idx
                })
                position = 0

        elif position == -1:
            hit_sl = high[i] >= entry_price * (1 + sl_pct)
            hit_tp = low[i] <= entry_price * (1 - tp_pct)
            if hit_sl or hit_tp or sig[i] != -1:
                if hit_sl:
                    exit_p = entry_price * (1 + sl_pct)
                    reason = "SL"
                elif hit_tp:
                    exit_p = entry_price * (1 - tp_pct)
                    reason = "TP"
                else:
                    exit_p = close[i]
                    reason = "Signal"
                ret = (entry_price / exit_p - 1) - 2 * cost
                trades.append({
                    "entry_time": entry_time,
                    "exit_time": times[i],
                    "direction": "SHORT",
                    "entry_price": round(entry_price, 2),
                    "exit_price": round(exit_p, 2),
                    "return_%": round(ret * 100, 3),
                    "result": "WIN" if ret > 0 else "LOSS",
                    "reason": reason,
                    "bars_held": i - entry_idx
                })
                position = 0

    trades_df = pd.DataFrame(trades)

    if len(trades_df) == 0:
        print("Δεν βρέθηκαν συναλλαγές!")
        return None, trades_df

    total_trades = len(trades_df)
    wins = (trades_df["result"] == "WIN").sum()
    losses = total_trades - wins
    winrate = wins / total_trades * 100
    total_return = trades_df["return_%"].sum()
    avg_return = trades_df["return_%"].mean()
    pos_sum = trades_df.loc[trades_df["return_%"] > 0, "return_%"].sum()
    neg_sum = abs(trades_df.loc[trades_df["return_%"] < 0, "return_%"].sum())
    profit_factor = pos_sum / neg_sum if neg_sum > 0 else np.inf

    print("\n" + "="*70)
    print("ΣΥΝΟΨΗ ΣΥΝΑΛΛΑΓΩΝ")
    print("="*70)
    print(f"Συνολικές συναλλαγές : {total_trades}")
    print(f"Κερδισμένες (WIN)     : {wins}")
    print(f"Χαμένες (LOSS)        : {losses}")
    print(f"Win Rate              : {winrate:.1f}%")
    print(f"Συνολικό αποτέλεσμα   : {total_return:+.2f}%")
    print(f"Μέσο αποτέλεσμα/trade : {avg_return:+.3f}%")
    print(f"Profit Factor         : {profit_factor:.2f}")
    print("="*70)

    return {"total_trades": total_trades, "winrate": winrate, "total_return_%": total_return}, trades_df

# ---------- 5. Τρέξε το backtest ----------
metrics, trades_df = backtest_with_trades(df, signal)

print("\nΑναλυτική λίστα όλων των συναλλαγών:")
display(trades_df)